[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
sol_pot = "2osXrDKHFiDhuMA8exFP65qnyg4D2QjV5eNxhWnzXe8z"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
